-- MySQL Script generated by MySQL Workbench
-- 03/01/15 20:14:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema edificio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema edificio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `edificio` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `edificio` ;

-- -----------------------------------------------------
-- Table `edificio`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`infoInquilino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`infoInquilino` (
  `CURP` VARCHAR(18) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `aPaterno` VARCHAR(45) NOT NULL,
  `aMaterno` VARCHAR(45) NULL,
  `pass` VARCHAR(100) NOT NULL,
  `rol_idrol` INT NOT NULL,
  PRIMARY KEY (`CURP`),
  INDEX `fk_infoInquilino_rol` (`rol_idrol` ASC),
  CONSTRAINT `fk_infoInquilino_rol`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `edificio`.`rol` (`idrol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`estatusDep`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`estatusDep` (
  `idestatusDep` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idestatusDep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`edificio` (
  `nEdificio` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`nEdificio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`departamento` (
  `nDepartamento` INT NOT NULL AUTO_INCREMENT,
  `tamaño` VARCHAR(45) NULL,
  `estatusDep_idestatusDep` INT NOT NULL,
  `edificio_nEdificio` INT NOT NULL,
  PRIMARY KEY (`nDepartamento`),
  INDEX `fk_departamento_estatusDep1` (`estatusDep_idestatusDep` ASC),
  INDEX `fk_departamento_edificio1` (`edificio_nEdificio` ASC),
  CONSTRAINT `fk_departamento_estatusDep1`
    FOREIGN KEY (`estatusDep_idestatusDep`)
    REFERENCES `edificio`.`estatusDep` (`idestatusDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departamento_edificio1`
    FOREIGN KEY (`edificio_nEdificio`)
    REFERENCES `edificio`.`edificio` (`nEdificio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`inquilino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`inquilino` (
  `idinquilino` INT NOT NULL AUTO_INCREMENT,
  `fechaAlta` DATE NOT NULL,
  `fechaBaja` DATE NULL,
  `infoInquilino_CURP` VARCHAR(18) NOT NULL,
  `departamento_nDepartamento` INT NOT NULL,
  PRIMARY KEY (`idinquilino`, `infoInquilino_CURP`),
  INDEX `fk_inquilino_infoInquilino1` (`infoInquilino_CURP` ASC),
  INDEX `fk_inquilino_departamento1` (`departamento_nDepartamento` ASC),
  CONSTRAINT `fk_inquilino_infoInquilino1`
    FOREIGN KEY (`infoInquilino_CURP`)
    REFERENCES `edificio`.`infoInquilino` (`CURP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inquilino_departamento1`
    FOREIGN KEY (`departamento_nDepartamento`)
    REFERENCES `edificio`.`departamento` (`nDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`servicio` (
  `idservicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idservicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`detallePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`detallePago` (
  `idDetalle` INT NOT NULL AUTO_INCREMENT,
  `costo` FLOAT NOT NULL,
  `fechaLimite` DATE NOT NULL,
  `recibo` LONGBLOB NULL,
  PRIMARY KEY (`idDetalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`pagoServicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`pagoServicio` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `departamento_nDepartamento` INT NOT NULL,
  `servicio_idservicio` INT NOT NULL,
  `monto` FLOAT NOT NULL,
  `pagado` TINYINT(1) NOT NULL,
  `fechaPago` DATE NULL,
  `detallePago_idDetalle` INT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_servicio_has_departamento_departamento1` (`departamento_nDepartamento` ASC),
  INDEX `fk_pagoServicio_servicio1` (`servicio_idservicio` ASC),
  INDEX `pago_mes` (`servicio_idservicio` ASC),
  INDEX `fk_pagoServicio_detallePago1_idx` (`detallePago_idDetalle` ASC),
  CONSTRAINT `fk_servicio_has_departamento_departamento1`
    FOREIGN KEY (`departamento_nDepartamento`)
    REFERENCES `edificio`.`departamento` (`nDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagoServicio_servicio1`
    FOREIGN KEY (`servicio_idservicio`)
    REFERENCES `edificio`.`servicio` (`idservicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagoServicio_detallePago1`
    FOREIGN KEY (`detallePago_idDetalle`)
    REFERENCES `edificio`.`detallePago` (`idDetalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`motivoMulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`motivoMulta` (
  `idmotivoMulta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `costo` FLOAT NOT NULL,
  PRIMARY KEY (`idmotivoMulta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`multa` (
  `idmulta` INT NOT NULL AUTO_INCREMENT,
  `pagado` TINYINT(1) NULL,
  `fechaMulta` DATE NOT NULL,
  `fechaPago` DATE NULL,
  `departamento_nDepartamento` INT NOT NULL,
  `motivoMulta_idmotivoMulta` INT NOT NULL,
  PRIMARY KEY (`idmulta`),
  INDEX `fk_multa_departamento1` (`departamento_nDepartamento` ASC),
  INDEX `fk_multa_motivoMulta1` (`motivoMulta_idmotivoMulta` ASC),
  CONSTRAINT `fk_multa_departamento1`
    FOREIGN KEY (`departamento_nDepartamento`)
    REFERENCES `edificio`.`departamento` (`nDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_multa_motivoMulta1`
    FOREIGN KEY (`motivoMulta_idmotivoMulta`)
    REFERENCES `edificio`.`motivoMulta` (`idmotivoMulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `edificio`.`queja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `edificio`.`queja` (
  `idQueja` INT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(45) NOT NULL,
  `queja` VARCHAR(100) NOT NULL,
  `fechaQueja` DATE NOT NULL,
  `departamento_nDepartamento` INT NOT NULL,
  PRIMARY KEY (`idQueja`),
  INDEX `fk_queja_departamento1` (`departamento_nDepartamento` ASC),
  CONSTRAINT `fk_queja_departamento1`
    FOREIGN KEY (`departamento_nDepartamento`)
    REFERENCES `edificio`.`departamento` (`nDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
